"""empty message

Revision ID: 36900f252513
Revises: 2ce68d2cde20
Create Date: 2020-05-20 10:19:56.856829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36900f252513'
down_revision = '2ce68d2cde20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # op.alter_column('todos', 'completed', default=False)
    op.alter_column('todos', 'completed', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
