"""empty message

Revision ID: 928bcacf48d7
Revises: 36900f252513
Create Date: 2020-05-20 21:49:24.555716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928bcacf48d7'
down_revision = '36900f252513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
